"""Runtime control boundary."""

from __future__ import annotations

from aa.control.campaign import (
    AGGREGATE_REQUESTED_SECONDS,
    CAMPAIGN_LIFETIME_SECONDS,
    CONTROL_ISSUE_NUMBER,
    JOB_TIMEOUT_MINUTES,
    MAX_STARTS,
    RECONCILE_MINUTES,
    RUN_COMMAND,
    RUNNER_CEILING_MINUTES,
    RUNTIME_SECONDS,
    STATUS_COMMAND,
    STOP_COMMAND,
)

__all__ = [
    "AGGREGATE_REQUESTED_SECONDS",
    "CAMPAIGN_LIFETIME_SECONDS",
    "CONTROL_ISSUE_NUMBER",
    "JOB_TIMEOUT_MINUTES",
    "MAX_STARTS",
    "RECONCILE_MINUTES",
    "RUN_COMMAND",
    "RUNTIME_SECONDS",
    "RUNNER_CEILING_MINUTES",
    "STATUS_COMMAND",
    "STOP_COMMAND",
]
